# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import csv
from PyQt5.QtWidgets import QWidget, QListWidget, QPushButton, QFileDialog, QMessageBox, QApplication, QVBoxLayout
from PyQt5.QtCore import Qt

class Window(QWidget):
    def __init__(self):
        super().__init__()

        self.list = QListWidget()
        self.button = QPushButton("选择CSV文件")
        self.button.clicked.connect(self.get_file)

        layout = QVBoxLayout()
        layout.addWidget(self.list)
        layout.addWidget(self.button)
        self.setLayout(layout)

    def get_file(self):
        fname = QFileDialog.getOpenFileName(self, 'Open CSV', 'c:\\', 'CSV Files (*.csv)')
        if fname[0]:
            with open(fname[0], encoding='utf-8') as f:
                csv_reader = csv.reader(f)
                for row in csv_reader:
                    self.list.addItem(' '.join(row))
        else:
            QMessageBox.warning(self, 'Warning', '未选择CSV文件!')

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())